import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import fs from 'node:fs/promises';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const {default:worker,token,validToken}=await import('../dist/worker.mjs');
const env={WORKSHOP_PASSWORD:'test-only-password',SESSION_SECRET:'test-only-long-signing-secret',LOGIN_LIMITER:{limit:async()=>({success:true})}};
const get=(path,cookie)=>new Request('https://seminar.example'+path,{headers:cookie?{Cookie:cookie}:{}});
const post=(password,origin='https://seminar.example')=>new Request('https://seminar.example/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({password})});
test('every asset and direct download requires authentication',async()=>{for(const path of ['/content.json','/app.js','/style.css','/index.html','/logos/excel.svg','/logos/chatgpt.png','/material/04-materialvergleich.xlsx','/material/05-projektbogen.docx','/material/workshop-material.zip'])assert.equal((await worker.fetch(get(path),env)).status,401)});
test('login gives secure signed cookie and enables assets',async()=>{const r=await worker.fetch(post(env.WORKSHOP_PASSWORD),env);assert.equal(r.status,303);const cookie=r.headers.get('set-cookie');for(const flag of ['HttpOnly','Secure','SameSite=Strict'])assert.ok(cookie.includes(flag));assert.equal((await worker.fetch(get('/content.json',cookie.split(';')[0]),env)).status,200)});
test('wrong password and cross-origin requests rejected',async()=>{assert.equal((await worker.fetch(post('wrong'),env)).status,401);assert.equal((await worker.fetch(post(env.WORKSHOP_PASSWORD,'https://evil.example'),env)).status,403)});
test('rate limit response and missing config fail closed',async()=>{assert.equal((await worker.fetch(post('wrong'),{...env,LOGIN_LIMITER:{limit:async()=>({success:false})}})).status,429);assert.equal((await worker.fetch(get('/'),{})).status,503)});
test('tampered expired and future sessions rejected',async()=>{assert.equal(await validToken(await token(env.SESSION_SECRET,1),env.SESSION_SECRET),false);const t=await token(env.SESSION_SECRET);assert.equal(await validToken(t+'x',env.SESSION_SECRET),false);assert.equal(await validToken(t,'other'),false);assert.equal(await validToken(await token(env.SESSION_SECRET,Math.floor(Date.now()/1000)+999999),env.SESSION_SECRET),false)});
test('all workbook and document downloads exist and are ZIP containers',async()=>{const c='seminar_session='+await token(env.SESSION_SECRET);for(const path of ['/material/04-materialvergleich.xlsx','/material/05-projektbogen.docx','/material/workshop-material.zip']){const r=await worker.fetch(get(path,c),env);assert.equal(r.status,200);assert.equal(new TextDecoder().decode((await r.arrayBuffer()).slice(0,2)),'PK')}});
test('34 slides and independently usable challenges',async()=>{const c=JSON.parse(await fs.readFile('public/content.json','utf8'));assert.equal(c.slides.length,34);assert.equal(c.slides.filter(s=>s.type==='challenge').length,10);for(const s of c.slides.filter(s=>s.type==='challenge')){assert.ok(s.goal);assert.ok(s.criteria);assert.equal(s.hints.length,1)}});

test('preparation link keeps destination through login',async()=>{const page=await worker.fetch(get('/vorbereitung.html'),env);assert.equal(page.status,200);assert.match(await page.text(),/next=vorbereitung/);const request=new Request('https://seminar.example/login?next=vorbereitung',{method:'POST',headers:{Origin:'https://seminar.example'},body:new URLSearchParams({password:env.WORKSHOP_PASSWORD})});const result=await worker.fetch(request,env);assert.equal(result.headers.get('location'),'/vorbereitung.html');const checklist=await worker.fetch(get('/vorbereitung.html',result.headers.get('set-cookie').split(';')[0]),env);assert.match(await checklist.text(),/ITP Consultants kontaktieren/)});
