"""Single source of participant-facing content. Build with python3 scripts/content.py."""
from pathlib import Path
import json
from walkthroughs import walkthroughs
modules=[
 dict(name='Mit Work anfangen',app='chatgpt',title='Work hilft dir, Arbeit zu erledigen.',explain='Du beschreibst eine Aufgabe in deinen eigenen Worten. Work macht daraus zum Beispiel einen Text, eine Liste oder eine Datei.',example='Aus Notizen wird eine Aufgabenliste.',benefit='Du musst deine Stichpunkte nicht selbst sortieren.',inputTitle='Deine Notizen',input=['Lindenhof zurückrufen','Lieferung nachfragen','Drei Angebote vergleichen'],prompt='Mach aus diesen Notizen eine übersichtliche Aufgabenliste. Schreib zu jedem Punkt, was ich als Nächstes tun sollte.',outputTitle='Deine Aufgabenliste',output=['Lindenhof: Anlass des Rückrufs klären.','Lieferung: Status beim Lieferanten erfragen.','Angebote: Preise und Lieferkosten vergleichen.'],check='Sind alle drei Punkte dabei? Dann kannst du mit der Liste weiterarbeiten.',task='Lade die Tagesnotizen in Work und lass daraus eine Aufgabenliste erstellen.',success=['Alle Notizen tauchen wieder auf.','Du verstehst, was als Nächstes zu tun ist.'],file='01-tagesnotizen.txt',kind='notes'),
 dict(name='Bessere Antworten bekommen',app='chatgpt',title='Sag Work, was du anders brauchst.',explain='Die erste Antwort muss nicht perfekt sein. Du kannst sie kürzer, freundlicher oder genauer machen lassen – direkt in derselben Aufgabe.',example='Eine zu lange Mail wird kurz und klar.',benefit='Du verbesserst die Antwort, ohne neu anzufangen.',inputTitle='Der erste Entwurf',input=['Vielen Dank für Ihre ausführliche Nachricht und das entgegengebrachte Vertrauen. Sehr gern möchten wir Sie bei Ihrem geplanten Vorhaben unterstützen und gemeinsam die nächsten Schritte besprechen …'],prompt='Bitte kürzer: höchstens drei Sätze. Frage nach einem passenden Termin für eine Besichtigung. Sage noch keinen Termin zu.',outputTitle='Der bessere Entwurf',output=['Vielen Dank für Ihre Anfrage. Gern besichtigen wir die Räume, bevor wir ein Angebot erstellen. Wann würde Ihnen ein Termin passen?'],check='Ist die Mail kurz und freundlich? Ist klar, dass der Termin noch offen ist?',task='Öffne den fehlerhaften Mailentwurf. Lass Work daraus eine kurze Antwort ohne erfundene Zusagen machen.',success=['Keine erfundenen Preise oder Termine.','Die Antwort passt zur Kundenanfrage.'],file='02-fehlerhafter-entwurf.txt',kind='mail'),
 dict(name='Projekte verstehen',app='chatgpt',title='Ein Projekt hält deine Arbeit zusammen.',explain='Für einen Kundenauftrag brauchst du oft mehrere Dateien und Gespräche. Ein Projekt hilft dir, diese Dinge an einem Ort zu organisieren.',example='Alles für den Kunden Lindenhof.',benefit='Du findest die Unterlagen wieder und musst den Hintergrund nicht jedes Mal neu zusammensuchen.',inputTitle='Das gehört zusammen',input=['Die Anfrage von Lindenhof','Die Angaben zum Bauvorhaben','Deine Regeln für Kundenantworten'],prompt='Fasse die Lindenhof-Unterlagen zusammen. Was wissen wir schon, und welche Angaben fehlen noch?',outputTitle='Projekt Lindenhof',output=['Geplant: zwei Büroräume modernisieren.','Angefragt: Trennwände und zwei Innentüren.','Noch offen: Maße, Zugang und Ausführungstermin.'],check='Prüfe bei einer neuen Aufgabe, ob Work die richtigen Projektunterlagen tatsächlich verwendet.',task='Lege ein Projekt für Lindenhof an. Füge die Übungsunterlagen hinzu und lass dir den Auftrag kurz erklären.',success=['Du findest die Unterlagen im Projekt wieder.','Die Zusammenfassung passt zu den Unterlagen.'],file='03-lindenhof.txt',kind='project'),
 dict(name='Plugins verstehen',app='chatgpt',apps=['outlook','onedrive','excel'],title='Plugins verbinden Work mit deinen Programmen.',explain='Ein Plugin ist eine Erweiterung. Damit kann Work zum Beispiel in verbundenen Mails oder Dateien nach Informationen suchen. Die Einrichtung klärst du vorab mit ITP.',example='Eine Datei in OneDrive finden.',benefit='Du beschreibst, was du suchst, statt dich durch Ordner zu klicken.',inputTitle='Deine verbundenen Programme',input=['Outlook: Mails und Kalender','OneDrive: gespeicherte Dateien','Excel: Tabellen bearbeiten'],prompt='Suche im OneDrive-Übungsordner nach den Unterlagen zu Lindenhof. Zeige mir die passende Datei.',outputTitle='Gefundene Unterlage',output=['03-lindenhof.txt','Enthält: Kundenanfrage, Projektbrief und offene Fragen.'],check='Öffne die Datei und prüfe, ob es die richtige ist. Wenn Work nicht zugreifen kann, hilft ITP bei der Einrichtung.',task='Prüfe deine verbundenen Plugins. Lass Work eine bekannte Übungsdatei in OneDrive finden.',success=['Die richtige Verbindung ist eingerichtet.','Du kannst die gefundene Datei öffnen.'],file='03-lindenhof.txt',kind='connections'),
 dict(name='Mails verstehen & beantworten',app='outlook',apps=['outlook','chatgpt'],title='Von deiner heutigen Mail zur passenden Antwort.',explain='Wähle eine Mail, die du heute bekommen hast. Lass sie dir einfach erklären, eine Antwort formulieren und danach anpassen. Die fertige Fassung speicherst du als Outlook-Entwurf.',example='Eine heutige Mail. Eine verständliche Antwort.',benefit='Du verstehst, was gebraucht wird, und überarbeitest die Antwort direkt mit Work.',inputTitle='Heute im Posteingang',input=['Von Mara Sommer · Betreff: Besichtigung Lindenhof','„Könnten Sie uns sagen, welche Unterlagen Sie vor der Besichtigung benötigen?“'],prompt='Zeige mir die Mails, die ich heute bekommen habe, mit Absender und Betreff. Ich wähle danach eine aus.',outputTitle='Dein Antwortentwurf',output=['Danke für Ihre Nachricht. Bitte schicken Sie uns vorab einen Grundriss und Fotos der Räume. Wenn etwas davon fehlt, sagen Sie uns kurz Bescheid.'],check='Öffne den Entwurf in Outlook. Prüfe Empfänger, Inhalt und gegebenenfalls den Anhang. In dieser Übung bleibt die Antwort als Entwurf gespeichert.',task='Wähle eine Mail von heute aus deinem eigenen Posteingang. Lass Work sie erklären, eine Antwort formulieren und anschließend überarbeiten. Speichere die fertige Fassung als Outlook-Entwurf.',success=['Du kannst sagen, was der Absender von dir braucht.','Der überarbeitete Entwurf ist in Outlook gespeichert und von dir geprüft.'],file='03-lindenhof.txt',kind='mail-workflow',taskSteps=['Finden: Lass dir heutige Mails zeigen und wähle eine aus.','Verstehen: Was will der Absender? Was muss ich tun?','Entwerfen: Gib Work die nötigen Antwortinformationen und lass einen Antworttext formulieren.','Anpassen: Lass den Text kürzen oder den Ton ändern. Speichere ihn dann als Outlook-Entwurf und öffne ihn dort.'],taskNote='Wähle eine Mail, die du im Workshop verwenden darfst. Falls heute keine passende dabei ist, nutze die fiktive Lindenhof-Anfrage.',attachment='Optional: Lade eine passende Übungsdatei unter 3 MB in Work hoch. Bitte: „Hänge diese Datei an denselben Antwortentwurf an. Noch nicht versenden.“ Prüfe den Anhang anschließend in Outlook.',mailStages=[
 {'label':'Mail auswählen','heading':'Such dir eine heutige Mail aus.','prompt':'Zeige mir die Mails, die ich heute bekommen habe, mit Absender und Betreff. Ich wähle danach eine aus.','resultTitle':'Du wählst diese Mail','result':['Mara Sommer · Besichtigung Lindenhof','„Welche Unterlagen benötigen Sie vor der Besichtigung?“']},
 {'label':'Einfach erklären','heading':'Was will der Absender von dir?','prompt':'Erkläre mir die Mail von Mara Sommer zur Besichtigung in einfachen Worten. Was möchte sie von mir, und was muss ich als Nächstes tun?','resultTitle':'Einfach gesagt','result':['Mara möchte wissen, welche Unterlagen sie vorbereiten soll.','Du musst ihr sagen, welche Informationen du vor der Besichtigung brauchst.']},
 {'label':'Antwort entwerfen','heading':'Lass eine erste Antwort formulieren.','prompt':'Wir brauchen vorab einen Grundriss und Fotos der Räume. Formuliere dazu eine freundliche Antwort hier in Work. Noch nicht versenden.','resultTitle':'Erster Antwortvorschlag in Work','result':['Vielen Dank für Ihre Nachricht. Zur Vorbereitung der Besichtigung bitten wir Sie, uns einen Grundriss sowie Fotos der betreffenden Räume zu schicken. Falls Ihnen diese Unterlagen nicht vollständig vorliegen, geben Sie uns bitte kurz Bescheid.']},
 {'label':'Entwurf anpassen','heading':'Passe die Antwort an und speichere sie.','prompt':'Mach die Antwort kürzer und etwas lockerer, aber bleib bei „Sie“. Speichere die überarbeitete Fassung als Antwortentwurf in Outlook. Noch nicht versenden.','resultTitle':'Fertige Fassung als Outlook-Entwurf','result':['Danke für Ihre Nachricht. Bitte schicken Sie uns vorab einen Grundriss und Fotos der Räume. Wenn etwas davon fehlt, sagen Sie uns kurz Bescheid.']}
 ]),
 dict(name='Internet & Browser nutzen',app='chatgpt',title='Lass Work Informationen im Internet sammeln.',explain='Du gibst an, was du suchst. Work kann Informationen recherchieren und – wenn eingerichtet – mit dem Browser eine Website bedienen. Lass dir immer die Quellen zeigen.',example='Ein Büro mit Lager auf ImmoScout24 suchen.',benefit='Du bekommst eine Auswahl, die du selbst vergleichen kannst.',inputTitle='Deine Suche',input=['Büro mit Lager in Hamburg und Umgebung','80 bis 180 m²','Bis 2.000 € Nettokaltmiete'],prompt='Suche auf ImmoScout24 nach einem Büro mit Lager nach diesen Kriterien. Vergleiche bis zu drei Objekte und zeige die Links. Kontaktiere keine Anbieter.',outputTitle='So könnte der Vergleich aussehen',output=['Objekt A: 120 m² · 1.650 € kalt · Lager vorhanden','Objekt B: 95 m² · 1.400 € kalt · Lager unklar','Objekt C: 170 m² · 1.950 € kalt · Nebenkosten fehlen'],check='Öffne die Quellen selbst. Die hier gezeigten Objekte sind erfunden; bei deiner Suche verwendest du echte Links.',task='Suche mit Work einen geeigneten Standort. Vergleiche bis zu drei Treffer – oder nutze die fiktiven Ersatzobjekte aus der Übungsdatei.',success=['Du kannst die Angaben an der Quelle prüfen.','Unbekannte Kosten bleiben als offen markiert.'],file='06-standortsuche.txt',kind='browser'),
 dict(name='Excel einfacher nutzen',app='excel',apps=['excel','chatgpt'],title='Lass dir Tabellen erklären und auswerten.',explain='Du kannst eine Excel-Datei in Work hochladen oder die eingerichtete ChatGPT-Integration direkt in Excel nutzen. Du beschreibst in Worten, was du herausfinden möchtest.',example='Welches Materialangebot ist am günstigsten?',benefit='Du vergleichst die Gesamtkosten, ohne die Rechnung selbst aufbauen zu müssen.',inputTitle='Drei Angebote für 100 Stück',input=['A: 12,50 € je Stück + 80 € Lieferung','B: 12,90 € je Stück + 20 € Lieferung','C: 11,90 € je Stück + 160 € Lieferung'],prompt='Vergleiche die drei Angebote für 100 Stück. Rechne die Lieferkosten dazu und zeige mir das günstigste Angebot. Alle Preise sind netto.',outputTitle='Das Ergebnis inklusive Lieferung',output=['A: 1.330 €','B: 1.310 € – günstigstes Angebot','C: 1.350 €'],check='Rechne eine Zeile nach: 100 × 12,90 € + 20 € = 1.310 €. Prüfe zusätzlich die Lieferzeit.',task='Öffne den Materialvergleich. Finde mit KI das günstigste Angebot. Probiere danach den zweiten Weg: in Work oder direkt in Excel.',success=['Lieferkosten sind enthalten.','Du kannst eine Rechnung nachvollziehen.'],file='04-materialvergleich.xlsx',kind='excel'),
 dict(name='Dokumente ausfüllen',app='word',apps=['word','chatgpt'],title='Work kann Angaben in eine Vorlage übertragen.',explain='Gib Work die Vorlage und die Informationen, die eingetragen werden sollen. Du bekommst ein ausgefülltes Dokument und prüfst es anschließend.',example='Ein Projektbogen für Lindenhof.',benefit='Du überträgst dieselben Angaben nicht mehr Feld für Feld von Hand.',inputTitle='Was du mitgibst',input=['Leere Vorlage: Projektbogen.docx','Informationen: Lindenhof-Unterlagen'],prompt='Fülle den Projektbogen mit den Lindenhof-Angaben aus. Wenn eine Information fehlt, schreibe „noch offen“. Gib mir eine bearbeitbare Datei.',outputTitle='Der ausgefüllte Projektbogen',output=['Vorgang: LH-026','Ansprechpartnerin: Mara Sommer','Ausführungstermin: noch offen'],check='Öffne die fertige Datei. Stimmen die Angaben, und ist alles gut lesbar?',task='Lade den Projektbogen und die Lindenhof-Unterlagen in Work. Lass die Vorlage ausfüllen und öffne das Ergebnis.',success=['Die Angaben stimmen mit der Quelle überein.','Fehlende Angaben wurden nicht erfunden.'],file='05-projektbogen.docx',extraFile='03-lindenhof.txt',kind='document'),
 dict(name='Termine vorbereiten',app='outlook',title='Beschreibe den Termin, den du brauchst.',explain='Work kann mit deiner Kalenderverbindung einen Termin vorbereiten. Nenne Anlass, Dauer und Beteiligte. Ein freier Platz in deinem Kalender heißt noch nicht, dass alle Zeit haben.',example='Eine Baustellenbesprechung planen.',benefit='Aus einer kurzen Beschreibung wird ein übersichtlicher Terminvorschlag.',inputTitle='Dein Terminwunsch',input=['Baustellenbesprechung Lindenhof','45 Minuten · nächste Woche','Eigene Projektleitung und Kundin'],prompt='Bereite einen 45-minütigen Termin für die Besichtigung vor. Schlage eine Zeit vor und zeige die Details. Noch keine Einladung versenden.',outputTitle='Der Terminvorschlag',output=['Besichtigung Lindenhof · 45 Minuten','Agenda: Maße, Zugang und offene Fragen','Datum und Verfügbarkeit der Kundin: noch abstimmen'],check='Prüfe Datum, Uhrzeit, Ort und Personen. Erst danach darf eine Einladung rausgehen.',task='Bereite anhand des Terminbriefs eine Besichtigung vor. Prüfe die Details. Ein Testtermin bleibt in deinem eigenen Kalender.',success=['Datum, Dauer und Ort sind eindeutig.','Unbekannte Verfügbarkeiten sind gekennzeichnet.'],file='07-terminbrief.txt',kind='calendar'),
 dict(name='Aufgaben später erledigen lassen',app='chatgpt',title='Du kannst Arbeit für später planen.',explain='Eine Erinnerung weist dich auf etwas hin. Eine geplante KI-Aufgabe bearbeitet einen Auftrag zu einer bestimmten Zeit – wenn diese Funktion in deinem Konto verfügbar ist.',example='Montags die offenen Aufgaben zusammenfassen.',benefit='Du musst denselben Auftrag nicht jede Woche neu schreiben.',inputTitle='Was regelmäßig anfällt',input=['Übungsprojekt Lindenhof öffnen','Offene Aufgaben sammeln','Eine kurze Zusammenfassung lesen'],prompt='Fasse vier Wochen lang montags um 08:30 Uhr die offenen Aufgaben im Übungsprojekt Lindenhof zusammen. Zeitzone: Europe/Berlin. Zeige mir zuerst die Einrichtung.',outputTitle='So ist die Aufgabe geplant',output=['Wann: montags, 08:30 Uhr · Europe/Berlin','Was: offene Punkte aus Lindenhof zusammenfassen','Wie lange: vier Wochen'],check='Prüfe die gespeicherte Aufgabe. Nach dem Workshop deaktivierst du die Übung wieder.',task='Formuliere eine Erinnerung und eine wiederkehrende Aufgabe. Richte eine davon ein, wenn dein Konto die Funktion unterstützt, und prüfe sie.',success=['Es ist klar, was wann passieren soll.','Du weißt, wo du die Aufgabe wieder ausschaltest.'],file='07-terminbrief.txt',kind='schedule')
]
guided=walkthroughs(modules)
for i,m in enumerate(modules,1):m['walkthrough']=guided[i]
modules[2]['explain']='Ein Projekt ist wie eine Arbeitsmappe für einen Kundenauftrag. Es hält Unterlagen, Gespräche und gemeinsame Vorgaben zusammen. Du legst es einmal an und öffnest es wieder, wenn du am selben Auftrag weiterarbeitest.'
modules[2]['task']='Lege ein Projekt „Lindenhof · Umbau“ an, füge die Lindenhof-Datei hinzu und speichere eine kurze Vorgabe für Kundenantworten. Starte darin eine Work-Aufgabe und lass den Auftrag zusammenfassen.'
modules[2]['success']=['Du findest das Projekt mit der Datei und deiner Vorgabe wieder.','Deine Work-Aufgabe verwendet die Lindenhof-Unterlagen.']
slides=[dict(id=1,type='hero',title='KI für deinen Arbeitsalltag.',lead='Heute machen wir ganz normale Büroarbeit einfacher.',chapter=0,chapterName='Willkommen',paragraphs=[]),dict(id=2,type='prep',title='Vor dem Seminar: einmal alles testen.',lead='Wenn etwas fehlt, kontaktiere ITP.',chapter=0,chapterName='Vorbereitung',paragraphs=[]),dict(id=3,type='intro',title='Du musst keine Technik lernen.',lead='Du sagst, was du brauchst. Wir schauen uns ein Beispiel an. Dann probierst du es selbst.',chapter=0,chapterName='So läuft es ab',paragraphs=['Wir starten mit erfundenen Daten aus einem Handwerksbetrieb. Bei der Mail-Übung kannst du eine passende eigene Mail von heute verwenden oder unser fiktives Beispiel nutzen.'])]
for i,m in enumerate(modules,1):
 for typ in ['lesson','demo','challenge']:
  s=dict(m,id=len(slides)+1,type=typ,chapter=i,chapterName=m['name'],lead=m['title'],paragraphs=[m['explain']],steps=['Deine Unterlagen','Dein Auftrag','Das Ergebnis','Kurz prüfen'],goal=m['task'],criteria='; '.join(m['success']),hints=[m['prompt']],bonus='')
  if typ=='demo':s['title']=m['example'];s['lead']=m['example']
  if typ=='challenge':s['title']='Jetzt probierst du es.';s['lead']=m['task']
  slides.append(s)
slides.append(dict(id=len(slides)+1,type='outro',title='Welche Aufgabe wird morgen einfacher?',lead='Such dir eine Sache aus deinem Arbeitsalltag aus. Genau damit fängst du an.',chapter=0,chapterName='Zum Abschluss',paragraphs=['Wenn du mehrere Themen kombinieren möchtest, probiere die freiwillige Abschlussaufgabe Parkblick.']))
prep=[
 {'group':'Mitbringen','items':['Laptop und Ladegerät sind dabei.','Ich kann mich ins WLAN einloggen. Mein Handy für Anmeldecodes ist griffbereit.']},
 {'group':'Zugänge testen','items':['Die ChatGPT-Desktop-App ist auf meinem Laptop installiert. Ich kann mich mit meinem eigenen Konto anmelden und ChatGPT öffnen. Falls ich Hilfe bei der Installation brauche, wende ich mich an Kerim.','Meine Lizenz und die benötigten Funktionen wurden geprüft. Bei Fragen zur Einrichtung kontaktiere ich ITP Consultants.']},
 {'group':'Microsoft 365 verbinden','items':['Outlook Mail: ChatGPT findet eine Testmail und kann einen ungesendeten Übungsentwurf an meine eigene Adresse speichern.','Outlook Kalender: ChatGPT kann meinen Kalender lesen und einen eigenen Übungstermin ohne Gäste anlegen, verschieben und wieder löschen.','OneDrive: ChatGPT kann eine Testdatei im eigenen Übungsordner öffnen und eine neue Datei dort speichern.','Excel: Ich kann eine Datei öffnen. Die ChatGPT-Integration direkt in Excel ist eingerichtet und einmal getestet.']},
 {'group':'Kurz ausprobieren','items':['Ich kann eine Datei in ChatGPT hochladen und eine erzeugte Datei herunterladen.','Der Browser in ChatGPT kann eine Website öffnen.','Die Funktion für geplante Aufgaben wurde geprüft. Falls sie fehlt, kläre ich das vorab mit ITP Consultants.','Ich kann die Seminarwebsite öffnen und das Übungspaket herunterladen.']},
 {'group':'Für die Organisation','items':['Beamer oder großer Bildschirm, Strom und stabiles WLAN sind bereit.','Die benötigten Kontofreigaben wurden vorab mit ITP Consultants geklärt.','Die Übungsdateien stehen bereit. Es werden keine echten Kundendaten benötigt.']}
]
Path('public/content.json').write_text(json.dumps({'version':3,'chapters':['Start & Vorbereitung']+[m['name'] for m in modules],'slides':slides,'preparation':prep},ensure_ascii=False,indent=2))
check='CHECKLISTE VOR DEM KI-SEMINAR\n\nBitte einige Tage vorher prüfen. Wenn etwas fehlt oder nicht funktioniert: ITP Consultants kontaktieren.\n\n'
for g in prep:
 check+=g['group'].upper()+'\n'+''.join('[ ] '+x+'\n' for x in g['items'])+'\n'
check+='Du brauchst keine Vorkenntnisse. Die Übungsdateien sind fiktiv. Für die Mail-Übung kannst du eine passende eigene Mail von heute oder das fiktive Ersatzbeispiel verwenden.\nPasswörter nicht in diese Checkliste eintragen.\n'
Path('public/material/00-vorbereitung.txt').write_text(check)
print(len(slides),'verständliche Szenen; 10 Beispiele; 10 Aufgaben; Vorbereitungsliste')
