import fs from 'node:fs/promises';
const {Workbook,SpreadsheetFile}=await import(process.env.ARTIFACT_TOOL_MODULE || '@oai/artifact-tool');
const wb=Workbook.create();const offers=wb.worksheets.add('Angebote'),raw=wb.worksheets.add('Materialliste'),calc=wb.worksheets.add('Rechenbeispiel');
for(const sheet of [offers,raw,calc]){sheet.showGridLines=false;sheet.getRange('A1:F16').format.font={name:'Arial',size:11};sheet.getRange('A1:F16').format.rowHeight=26;sheet.getRange('A1:F16').format.columnWidth=22;sheet.getRange('A1').format.font={size:18,bold:true};}
offers.getRange('A1').values=[['Materialangebote']];offers.getRange('A2').values=[['Fiktive Übungsdaten. 100 gleiche Einheiten. Alle Preise netto.']];offers.getRange('A4:F7').values=[['Anbieter','Menge','Einheit','Preis je Stück','Lieferkosten','Lieferzeit'],['A',100,'Stück',12.5,80,'10 Werktage'],['B',100,'Stück',12.9,20,'8 Werktage'],['C',100,'Stück',11.9,160,'offen']];offers.getRange('D5:E7').setNumberFormat('#,##0.00 "€"');offers.getRange('A10').values=[['Aufgabe: Gesamtkosten vergleichen und offene Bedingungen benennen.']];offers.getRange('A11').values=[['Bei 200 Einheiten: Lieferkosten nur als ausdrückliche Annahme konstant halten.']];
raw.getRange('A1').values=[['Materialliste bereinigen']];raw.getRange('A2').values=[['Fiktive Rohdaten mit absichtlichen Schreib- und Datentypfehlern.']];raw.getRange('A4:E9').values=[['Position','Bezeichnung','Menge','Einheit','Hinweis'],['M-01','Montageeinheit',40,'Stück','Bereich 1'],['M-02',' montageeinheit ','30','Stk.','Bereich 2'],['M-03','MONTAGEEINHEIT',30,'Stück','Bereich 3'],['M-04','Dichtband',5,'Rollen','Nicht im Angebotsvergleich'],['M-05','Abdeckfolie',2,'Rollen','Nicht im Angebotsvergleich']];raw.getRange('A12').values=[['Aufgabe: Schreibweisen vereinheitlichen, Mengen prüfen und Original erhalten.']];
calc.getRange('A1').values=[['Rechenbeispiel zur Kontrolle']];calc.getRange('A2').values=[['Nach dem eigenen Versuch ansehen. Ändere die Menge und prüfe die Wirkung.']];calc.getRange('A4:E7').values=[['Anbieter','Menge','Preis je Stück','Lieferkosten','Gesamt netto'],['A',100,12.5,80,null],['B',100,12.9,20,null],['C',100,11.9,160,null]];calc.getRange('E5').formulas=[['=B5*C5+D5']];calc.getRange('E5:E7').fillDown();calc.getRange('C5:E7').setNumberFormat('#,##0.00 "€"');calc.getRange('A10').values=[['Bei 100 Einheiten: Anbieter B hat den niedrigsten Materialgesamtpreis.']];calc.getRange('A11').values=[['Technische Eignung und Lieferzeit separat prüfen. Montage nicht enthalten.']];
for(const sheet of [offers,raw,calc]){const end=sheet===offers?'F':'E';sheet.getRange(`A4:${end}4`).format={fill:'#15161d',font:{name:'Arial',color:'#ffffff',bold:true},rowHeight:30};sheet.getRange(`A5:${end}9`).format.borders={insideHorizontal:{style:'thin',color:'#ececf0'}};sheet.freezePanes.freezeRows(4);}
raw.getRange('B1:B16').format.columnWidth=29;offers.getRange('A2:F2').merge();offers.getRange('A10:F10').merge();offers.getRange('A11:F11').merge();raw.getRange('A2:E2').merge();raw.getRange('A12:E12').merge();calc.getRange('A2:E2').merge();calc.getRange('A10:E10').merge();calc.getRange('A11:E11').merge();
await fs.mkdir('.qa/sheets',{recursive:true});
for(const sheet of [offers,raw,calc]){const image=await wb.render({sheetName:sheet.name,range:'A1:F13',scale:1.5});await fs.writeFile(`.qa/sheets/${sheet.name}.png`,new Uint8Array(await image.arrayBuffer()))}
console.log((await wb.inspect({kind:'table',range:'Rechenbeispiel!A4:E7',include:'values,formulas',tableMaxRows:4,tableMaxCols:5})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#SPILL!',options:{useRegex:true,maxResults:10},summary:'Formula check'})).ndjson);
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save('public/material/04-materialvergleich.xlsx');
